import type { Table } from '../../../../tables/dungeon/dungeonTypes';

export enum TreasureMiscMagicE2 {
  CandleOfInvocation,
  CarpetOfFlying,
  CenserControllingAirElementals,
  CenserOfSummoningHostileAirElementals,
  ChimeOfOpening,
  ChimeOfHunger,
  CloakOfDisplacement,
  CloakOfElvenkind,
  CloakOfMantaRay,
  CloakOfPoisonousness,
  CloakOfProtection,
  CrystalBall,
  CrystalHypnosisBall,
  CubeOfForce,
  CubeOfFrostResistance,
  CubicGate,
  DaernsInstantFortress,
  DecanterOfEndlessWater,
  DeckOfManyThings,
  DrumsOfDeafening,
  DrumsOfPanic,
  DustOfAppearance,
  DustOfDisappearance,
  DustOfSneezingAndChoking,
  EfreetiBottle,
  EversmokingBottle,
  EyesOfCharming,
  EyesOfTheEagle,
  EyesOfMinuteSeeing,
  EyesOfPetrification,
}

export const treasureMiscMagicE2: Table<TreasureMiscMagicE2> = {
  sides: 100,
  entries: [
    { range: [1, 6], command: TreasureMiscMagicE2.CandleOfInvocation },
    { range: [7, 8], command: TreasureMiscMagicE2.CarpetOfFlying },
    {
      range: [9, 10],
      command: TreasureMiscMagicE2.CenserControllingAirElementals,
    },
    {
      range: [11],
      command: TreasureMiscMagicE2.CenserOfSummoningHostileAirElementals,
    },
    { range: [12, 13], command: TreasureMiscMagicE2.ChimeOfOpening },
    { range: [14], command: TreasureMiscMagicE2.ChimeOfHunger },
    { range: [15, 18], command: TreasureMiscMagicE2.CloakOfDisplacement },
    { range: [19, 27], command: TreasureMiscMagicE2.CloakOfElvenkind },
    { range: [28, 30], command: TreasureMiscMagicE2.CloakOfMantaRay },
    { range: [31, 32], command: TreasureMiscMagicE2.CloakOfPoisonousness },
    { range: [33, 55], command: TreasureMiscMagicE2.CloakOfProtection },
    { range: [56, 60], command: TreasureMiscMagicE2.CrystalBall },
    { range: [61], command: TreasureMiscMagicE2.CrystalHypnosisBall },
    { range: [62, 63], command: TreasureMiscMagicE2.CubeOfForce },
    { range: [64, 65], command: TreasureMiscMagicE2.CubeOfFrostResistance },
    { range: [66, 67], command: TreasureMiscMagicE2.CubicGate },
    { range: [68, 69], command: TreasureMiscMagicE2.DaernsInstantFortress },
    { range: [70, 72], command: TreasureMiscMagicE2.DecanterOfEndlessWater },
    { range: [73, 76], command: TreasureMiscMagicE2.DeckOfManyThings },
    { range: [77], command: TreasureMiscMagicE2.DrumsOfDeafening },
    { range: [78, 79], command: TreasureMiscMagicE2.DrumsOfPanic },
    { range: [80, 85], command: TreasureMiscMagicE2.DustOfAppearance },
    { range: [86, 91], command: TreasureMiscMagicE2.DustOfDisappearance },
    {
      range: [92],
      command: TreasureMiscMagicE2.DustOfSneezingAndChoking,
    },
    { range: [93], command: TreasureMiscMagicE2.EfreetiBottle },
    { range: [94], command: TreasureMiscMagicE2.EversmokingBottle },
    { range: [95], command: TreasureMiscMagicE2.EyesOfCharming },
    { range: [96, 97], command: TreasureMiscMagicE2.EyesOfTheEagle },
    { range: [98, 99], command: TreasureMiscMagicE2.EyesOfMinuteSeeing },
    { range: [100], command: TreasureMiscMagicE2.EyesOfPetrification },
  ],
};

