import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum TreasureMiscMagicE3 {
  FigurineOfWondrousPower,
  FlaskOfCurses,
  GauntletsOfDexterity,
  GauntletsOfFumbling,
  GauntletsOfOgrePower,
  GauntletsOfSwimmingAndClimbing,
  GemOfBrightness,
  GemOfSeeing,
  GirdleOfFemininityMasculinity,
  GirdleOfGiantStrength,
  HelmOfBrilliance,
  HelmOfComprehendingLanguagesAndReadingMagic,
  HelmOfOppositeAlignment,
  HelmOfTelepathy,
  HelmOfTeleportation,
  HelmOfUnderwaterAction,
  HornOfBlasting,
  HornOfBubbles,
  HornOfCollapsing,
  HornOfTheTritons,
  HornOfValhalla,
  HorseshoesOfSpeed,
  HorseshoesOfAZephyr,
  IncenseOfMeditation,
  IncenseOfObsession,
  IounStones,
  InstrumentOfTheBards,
  IronFlask,
  JavelinOfLightning,
  JavelinOfPiercing,
  JewelOfAttacks,
  JewelOfFlawlessness,
  KeoghtomsOintment,
}

export const treasureMiscMagicE3: Table<TreasureMiscMagicE3> = {
  sides: 100,
  entries: [
    { range: [1, 15], command: TreasureMiscMagicE3.FigurineOfWondrousPower },
    { range: [16], command: TreasureMiscMagicE3.FlaskOfCurses },
    { range: [17, 18], command: TreasureMiscMagicE3.GauntletsOfDexterity },
    { range: [19, 20], command: TreasureMiscMagicE3.GauntletsOfFumbling },
    { range: [21, 22], command: TreasureMiscMagicE3.GauntletsOfOgrePower },
    {
      range: [23, 25],
      command: TreasureMiscMagicE3.GauntletsOfSwimmingAndClimbing,
    },
    { range: [26], command: TreasureMiscMagicE3.GemOfBrightness },
    { range: [27], command: TreasureMiscMagicE3.GemOfSeeing },
    {
      range: [28],
      command: TreasureMiscMagicE3.GirdleOfFemininityMasculinity,
    },
    { range: [29], command: TreasureMiscMagicE3.GirdleOfGiantStrength },
    { range: [30], command: TreasureMiscMagicE3.HelmOfBrilliance },
    {
      range: [31, 35],
      command: TreasureMiscMagicE3.HelmOfComprehendingLanguagesAndReadingMagic,
    },
    { range: [36, 37], command: TreasureMiscMagicE3.HelmOfOppositeAlignment },
    { range: [38, 39], command: TreasureMiscMagicE3.HelmOfTelepathy },
    { range: [40], command: TreasureMiscMagicE3.HelmOfTeleportation },
    { range: [41, 45], command: TreasureMiscMagicE3.HelmOfUnderwaterAction },
    { range: [46], command: TreasureMiscMagicE3.HornOfBlasting },
    { range: [47, 48], command: TreasureMiscMagicE3.HornOfBubbles },
    { range: [49], command: TreasureMiscMagicE3.HornOfCollapsing },
    { range: [50, 53], command: TreasureMiscMagicE3.HornOfTheTritons },
    { range: [54, 60], command: TreasureMiscMagicE3.HornOfValhalla },
    { range: [61, 63], command: TreasureMiscMagicE3.HorseshoesOfSpeed },
    { range: [64, 65], command: TreasureMiscMagicE3.HorseshoesOfAZephyr },
    { range: [66, 70], command: TreasureMiscMagicE3.IncenseOfMeditation },
    { range: [71], command: TreasureMiscMagicE3.IncenseOfObsession },
    { range: [72], command: TreasureMiscMagicE3.IounStones },
    { range: [73, 78], command: TreasureMiscMagicE3.InstrumentOfTheBards },
    { range: [79, 80], command: TreasureMiscMagicE3.IronFlask },
    { range: [81, 85], command: TreasureMiscMagicE3.JavelinOfLightning },
    { range: [86, 90], command: TreasureMiscMagicE3.JavelinOfPiercing },
    { range: [91], command: TreasureMiscMagicE3.JewelOfAttacks },
    { range: [92], command: TreasureMiscMagicE3.JewelOfFlawlessness },
    { range: [93, 100], command: TreasureMiscMagicE3.KeoghtomsOintment },
  ],
};
