import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum MonsterEight {
  AerialServant,
  Character,
  DemonTypeIV,
  DemonTypeV,
  DemonTypeVI,
  DevilIce,
  Dragon,
  Ghost,
  GiantCloud_1to2,
  GolemClay,
  Hydra_13to16Heads,
  HydraPyro_12Heads,
  IntellectDevourer_1to2,
  LurkerAbove,
  MoldBrown,
  MoldYellow,
  MindFlayer_1to4,
  NagaGuardian_1to2,
  NeoOtyugh,
  PurpleWorm,
  RustMonster,
  SlugGiant,
  Trapper,
  Vampire,
  WillOWisp_2to5,
  Xorn_2to5,
}

export const monsterEight: Table<MonsterEight> = {
  sides: 100,
  entries: [
    { range: [1], command: MonsterEight.AerialServant },
    { range: [2, 6], command: MonsterEight.Character },
    { range: [7], command: MonsterEight.DemonTypeIV },
    { range: [8], command: MonsterEight.DemonTypeV },
    { range: [9], command: MonsterEight.DemonTypeVI },
    { range: [10], command: MonsterEight.DevilIce },
    { range: [11, 12], command: MonsterEight.Dragon },
    { range: [13, 17], command: MonsterEight.Ghost },
    { range: [18, 21], command: MonsterEight.GiantCloud_1to2 },
    { range: [22, 23], command: MonsterEight.GolemClay },
    { range: [24, 26], command: MonsterEight.Hydra_13to16Heads },
    { range: [27], command: MonsterEight.HydraPyro_12Heads },
    { range: [28, 29], command: MonsterEight.IntellectDevourer_1to2 },
    { range: [30, 35], command: MonsterEight.LurkerAbove },
    { range: [36, 41], command: MonsterEight.MoldBrown },
    { range: [42, 43], command: MonsterEight.MoldYellow },
    { range: [44, 47], command: MonsterEight.MindFlayer_1to4 },
    { range: [48, 50], command: MonsterEight.NagaGuardian_1to2 },
    { range: [51, 56], command: MonsterEight.NeoOtyugh },
    { range: [57, 64], command: MonsterEight.PurpleWorm },
    { range: [65, 69], command: MonsterEight.RustMonster },
    { range: [70, 73], command: MonsterEight.SlugGiant },
    { range: [74, 78], command: MonsterEight.Trapper },
    { range: [79, 86], command: MonsterEight.Vampire },
    { range: [87, 92], command: MonsterEight.WillOWisp_2to5 },
    { range: [93, 100], command: MonsterEight.Xorn_2to5 },
  ],
};

export enum DragonEight {
  Black_Ancient_8,
  Blue_VeryOld_7,
  Brass_Ancient_8,
  Bronze_VeryOld_7,
  Copper_VeryOld_7,
  Gold_VeryOld_7,
  Green_VeryOld_7,
  Red_VeryOld_7,
  Silver_VeryOld_7,
  White_Ancient_8,
}

export const dragonEight: Table<DragonEight> = {
  sides: 100,
  entries: [
    { range: [1, 13], command: DragonEight.Black_Ancient_8 },
    { range: [14, 24], command: DragonEight.Blue_VeryOld_7 },
    { range: [25, 31], command: DragonEight.Brass_Ancient_8 },
    { range: [32, 35], command: DragonEight.Bronze_VeryOld_7 },
    { range: [36, 43], command: DragonEight.Copper_VeryOld_7 },
    { range: [44, 47], command: DragonEight.Gold_VeryOld_7 },
    { range: [48, 62], command: DragonEight.Green_VeryOld_7 },
    { range: [63, 78], command: DragonEight.Red_VeryOld_7 },
    { range: [79, 82], command: DragonEight.Silver_VeryOld_7 },
    { range: [83, 100], command: DragonEight.White_Ancient_8 },
  ],
};
