import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum TreasureMiscMagicE5 {
  RobeOfTheArchmagi,
  RobeOfBlending,
  RobeOfEyes,
  RobeOfPowerlessness,
  RobeOfScintillatingColors,
  RobeOfUsefulItems,
  RopeOfClimbing,
  RopeOfConstriction,
  RopeOfEntanglement,
  RugOfSmothering,
  RugOfWelcome,
  SawOfMightyCutting,
  ScarabOfDeath,
  ScarabOfEnragingEnemies,
  ScarabOfInsanity,
  ScarabOfProtection,
  SpadeOfColossalExcavation,
  SphereOfAnnihilation,
  StoneOfControllingEarthElementals,
  StoneOfGoodLuckLuckstone,
  StoneOfWeightLoadstone,
  TalismanOfPureGood,
  TalismanOfTheSphere,
  TalismanOfUltimateEvil,
  TalismanOfZagy,
  TomeOfClearThought,
  TomeOfLeadershipAndInfluence,
  TomeOfUnderstanding,
  TridentOfFishCommand,
  TridentOfSubmission,
  TridentOfWarning,
  TridentOfYearning,
  VacuousGrimoire,
  WellOfManyWorlds,
  WingsOfFlying,
}

export const treasureMiscMagicE5: Table<TreasureMiscMagicE5> = {
  sides: 100,
  entries: [
    { range: [1], command: TreasureMiscMagicE5.RobeOfTheArchmagi },
    { range: [2, 8], command: TreasureMiscMagicE5.RobeOfBlending },
    { range: [9], command: TreasureMiscMagicE5.RobeOfEyes },
    { range: [10], command: TreasureMiscMagicE5.RobeOfPowerlessness },
    { range: [11], command: TreasureMiscMagicE5.RobeOfScintillatingColors },
    { range: [12, 19], command: TreasureMiscMagicE5.RobeOfUsefulItems },
    { range: [20, 25], command: TreasureMiscMagicE5.RopeOfClimbing },
    { range: [26, 27], command: TreasureMiscMagicE5.RopeOfConstriction },
    { range: [28, 31], command: TreasureMiscMagicE5.RopeOfEntanglement },
    { range: [32], command: TreasureMiscMagicE5.RugOfSmothering },
    { range: [33], command: TreasureMiscMagicE5.RugOfWelcome },
    { range: [34], command: TreasureMiscMagicE5.SawOfMightyCutting },
    { range: [35], command: TreasureMiscMagicE5.ScarabOfDeath },
    { range: [36, 38], command: TreasureMiscMagicE5.ScarabOfEnragingEnemies },
    { range: [39, 40], command: TreasureMiscMagicE5.ScarabOfInsanity },
    { range: [41, 46], command: TreasureMiscMagicE5.ScarabOfProtection },
    {
      range: [47],
      command: TreasureMiscMagicE5.SpadeOfColossalExcavation,
    },
    { range: [48], command: TreasureMiscMagicE5.SphereOfAnnihilation },
    {
      range: [49, 50],
      command: TreasureMiscMagicE5.StoneOfControllingEarthElementals,
    },
    {
      range: [51, 52],
      command: TreasureMiscMagicE5.StoneOfGoodLuckLuckstone,
    },
    {
      range: [53, 54],
      command: TreasureMiscMagicE5.StoneOfWeightLoadstone,
    },
    { range: [55, 57], command: TreasureMiscMagicE5.TalismanOfPureGood },
    { range: [58], command: TreasureMiscMagicE5.TalismanOfTheSphere },
    { range: [59, 60], command: TreasureMiscMagicE5.TalismanOfUltimateEvil },
    { range: [61, 66], command: TreasureMiscMagicE5.TalismanOfZagy },
    { range: [67], command: TreasureMiscMagicE5.TomeOfClearThought },
    {
      range: [68],
      command: TreasureMiscMagicE5.TomeOfLeadershipAndInfluence,
    },
    { range: [69], command: TreasureMiscMagicE5.TomeOfUnderstanding },
    { range: [70, 76], command: TreasureMiscMagicE5.TridentOfFishCommand },
    { range: [77, 78], command: TreasureMiscMagicE5.TridentOfSubmission },
    { range: [79, 83], command: TreasureMiscMagicE5.TridentOfWarning },
    { range: [84, 85], command: TreasureMiscMagicE5.TridentOfYearning },
    { range: [86, 87], command: TreasureMiscMagicE5.VacuousGrimoire },
    { range: [88, 90], command: TreasureMiscMagicE5.WellOfManyWorlds },
    { range: [91, 100], command: TreasureMiscMagicE5.WingsOfFlying },
  ],
};
