import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum MonsterSix {
  Basilisk,
  CarrionCrawler_1to2,
  Character,
  DevilErinyes_1to2,
  Djinni,
  Dragon,
  GreenSlime,
  Hydra_8to9Heads,
  Jackalwere_1to2,
  Lammasu_1to3,
  LycanthropeWerebear,
  LycanthropeWeretiger_1to2,
  Manticore_1to2,
  Medusa,
  MoldBrown,
  MoldYellow,
  OgreMagi_1to2,
  Otyugh,
  Rakshasa,
  Salamander_1to2,
  SpiderPhase_1to3,
  Troll_1to3,
  Wight_1to4,
  WindWalker_1to2,
  Wraith_1to2,
  Wyvern,
}

export const monsterSix: Table<MonsterSix> = {
  sides: 100,
  entries: [
    { range: [1, 3], command: MonsterSix.Basilisk },
    { range: [4, 10], command: MonsterSix.CarrionCrawler_1to2 },
    { range: [11, 16], command: MonsterSix.Character },
    { range: [17], command: MonsterSix.DevilErinyes_1to2 },
    { range: [18, 19], command: MonsterSix.Djinni },
    { range: [20, 21], command: MonsterSix.Dragon },
    { range: [22, 25], command: MonsterSix.GreenSlime },
    { range: [26, 28], command: MonsterSix.Hydra_8to9Heads },
    { range: [29, 32], command: MonsterSix.Jackalwere_1to2 },
    { range: [33, 36], command: MonsterSix.Lammasu_1to3 },
    { range: [37, 38], command: MonsterSix.LycanthropeWerebear },
    { range: [39, 41], command: MonsterSix.LycanthropeWeretiger_1to2 },
    { range: [42, 50], command: MonsterSix.Manticore_1to2 },
    { range: [51, 55], command: MonsterSix.Medusa },
    { range: [56], command: MonsterSix.MoldBrown },
    { range: [57, 58], command: MonsterSix.MoldYellow },
    { range: [59, 60], command: MonsterSix.OgreMagi_1to2 },
    { range: [61, 68], command: MonsterSix.Otyugh },
    { range: [69, 70], command: MonsterSix.Rakshasa },
    { range: [71, 73], command: MonsterSix.Salamander_1to2 },
    { range: [74, 77], command: MonsterSix.SpiderPhase_1to3 },
    { range: [78, 88], command: MonsterSix.Troll_1to3 },
    { range: [89, 93], command: MonsterSix.Wight_1to4 },
    { range: [94, 95], command: MonsterSix.WindWalker_1to2 },
    { range: [96, 98], command: MonsterSix.Wraith_1to2 },
    { range: [99, 100], command: MonsterSix.Wyvern },
  ],
};

export enum DragonSix {
  Black_Old_6,
  Blue_Adult_5,
  Brass_Old_6,
  Bronze_Adult_5,
  Copper_Adult_5,
  Gold_Adult_5,
  Green_Adult_5,
  Red_Adult_5,
  Silver_Adult_5,
  White_Old_6,
}

export const dragonSix: Table<DragonSix> = {
  sides: 100,
  entries: [
    { range: [1, 8], command: DragonSix.Black_Old_6 },
    { range: [9, 19], command: DragonSix.Blue_Adult_5 },
    { range: [20, 29], command: DragonSix.Brass_Old_6 },
    { range: [30, 36], command: DragonSix.Bronze_Adult_5 },
    { range: [37, 48], command: DragonSix.Copper_Adult_5 },
    { range: [49, 52], command: DragonSix.Gold_Adult_5 },
    { range: [53, 65], command: DragonSix.Green_Adult_5 },
    { range: [66, 78], command: DragonSix.Red_Adult_5 },
    { range: [79, 87], command: DragonSix.Silver_Adult_5 },
    { range: [88, 100], command: DragonSix.White_Old_6 },
  ],
};
