import type { EncumbranceCatalogItem } from '../types/encumbrance';

const toGp = ({
  cp = 0,
  sp = 0,
  ep = 0,
  gp = 0,
  pp = 0,
}: {
  cp?: number;
  sp?: number;
  ep?: number;
  gp?: number;
  pp?: number;
}): number => cp / 100 + sp / 20 + ep / 2 + gp + pp * 5;

// Most valueGp figures below transcribe the PHB reference-sheet equipment page.
// Most encumbranceGp figures below transcribe DMG Appendix O.
// capacityGp and ammoCapacity are app rules, not PHB/DMG price-table text.
export const encumbranceCatalog: EncumbranceCatalogItem[] = [
  {
    id: 'backpack',
    name: 'Backpack',
    category: 'containers',
    encumbranceGp: 20,
    valueGp: toGp({ gp: 2 }),
    isContainer: true,
    capacityGp: 300,
  },
  {
    id: 'belt-pouch-small',
    name: 'Pouch, belt, small',
    category: 'containers',
    encumbranceGp: 5,
    valueGp: toGp({ sp: 15 }),
    isContainer: true,
    capacityGp: 25,
  },
  {
    id: 'belt-pouch-large',
    name: 'Pouch, belt, large',
    category: 'containers',
    encumbranceGp: 10,
    valueGp: toGp({ gp: 1 }),
    isContainer: true,
    capacityGp: 50,
  },
  // Questionable: convenience alias, not a literal PHB reference-sheet row.
  {
    id: 'purse',
    name: 'Purse',
    category: 'containers',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 10 }),
    isContainer: true,
    capacityGp: 25,
  },
  {
    id: 'sack-small',
    name: 'Sack, small',
    category: 'containers',
    encumbranceGp: 5,
    valueGp: toGp({ cp: 10 }),
    isContainer: true,
    capacityGp: 100,
  },
  {
    id: 'sack-large',
    name: 'Sack, large',
    category: 'containers',
    encumbranceGp: 20,
    valueGp: toGp({ cp: 16 }),
    isContainer: true,
    capacityGp: 400,
  },
  {
    id: 'quiver-arrows-12',
    name: 'Quiver (12 arrows)',
    category: 'containers',
    encumbranceGp: 30,
    valueGp: toGp({ sp: 8 }),
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'arrow',
      quantity: 12,
    },
  },
  {
    id: 'quiver-arrows-20',
    name: 'Quiver (20 arrows)',
    category: 'containers',
    encumbranceGp: 30,
    valueGp: toGp({ sp: 12 }),
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'arrow',
      quantity: 20,
    },
  },
  {
    id: 'quiver-bolts-20',
    name: 'Quiver (20 bolts)',
    category: 'containers',
    encumbranceGp: 30,
    valueGp: toGp({ sp: 15 }),
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'bolt',
      quantity: 20,
    },
  },
  {
    id: 'quiver-bolts-40',
    name: 'Quiver (40 bolts)',
    category: 'containers',
    encumbranceGp: 30,
    valueGp: toGp({ gp: 1 }),
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'bolt',
      quantity: 40,
    },
  },
  {
    id: 'armor-leather',
    name: 'Leather armor',
    category: 'armor',
    encumbranceGp: 150,
    valueGp: toGp({ gp: 5 }),
  },
  {
    id: 'armor-padded',
    name: 'Padded armor',
    category: 'armor',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 4 }),
  },
  {
    id: 'armor-ring',
    name: 'Ring mail',
    category: 'armor',
    encumbranceGp: 250,
    valueGp: toGp({ gp: 30 }),
  },
  {
    id: 'armor-studded',
    name: 'Studded leather',
    category: 'armor',
    encumbranceGp: 200,
    valueGp: toGp({ gp: 15 }),
  },
  {
    id: 'armor-scale',
    name: 'Scale mail',
    category: 'armor',
    encumbranceGp: 400,
    valueGp: toGp({ gp: 45 }),
  },
  {
    id: 'armor-chain',
    name: 'Chain mail',
    category: 'armor',
    encumbranceGp: 300,
    valueGp: toGp({ gp: 75 }),
  },
  {
    id: 'armor-splint',
    name: 'Splint mail',
    category: 'armor',
    encumbranceGp: 400,
    valueGp: toGp({ gp: 80 }),
  },
  {
    id: 'armor-banded',
    name: 'Banded mail',
    category: 'armor',
    encumbranceGp: 350,
    valueGp: toGp({ gp: 90 }),
  },
  {
    id: 'armor-plate',
    name: 'Plate mail',
    category: 'armor',
    encumbranceGp: 450,
    valueGp: toGp({ gp: 400 }),
  },
  {
    id: 'helmet-small',
    name: 'Helmet, small',
    category: 'armor',
    encumbranceGp: 45,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'helmet-great',
    name: 'Helmet, great',
    category: 'armor',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 15 }),
  },
  {
    id: 'shield-small',
    name: 'Shield, small',
    category: 'armor',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'shield-small-wood',
    name: 'Shield, small, wood',
    category: 'armor',
    encumbranceGp: 30,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'shield-large',
    name: 'Shield, large',
    category: 'armor',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 15 }),
  },
  {
    id: 'axe-battle',
    name: 'Axe, Battle',
    category: 'arms',
    encumbranceGp: 75,
    valueGp: toGp({ gp: 7 }),
  },
  {
    id: 'axe-hand',
    name: 'Axe, Hand',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'bardiche',
    name: 'Bardiche',
    category: 'arms',
    encumbranceGp: 125,
    valueGp: toGp({ gp: 7 }),
  },
  {
    id: 'bec-de-corbin',
    name: 'Bec de corbin',
    category: 'arms',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 6 }),
  },
  {
    id: 'bill-guisarme',
    name: 'Bill-Guisarme',
    category: 'arms',
    encumbranceGp: 150,
    valueGp: toGp({ gp: 6 }),
  },
  // Questionable: no explicit PHB purchase-price row; current value assumes an improvised/common club.
  {
    id: 'club',
    name: 'Club',
    category: 'arms',
    encumbranceGp: 30,
    valueGp: 0,
  },
  {
    id: 'dagger',
    name: 'Dagger and scabbard',
    category: 'arms',
    encumbranceGp: 10,
    valueGp: toGp({ gp: 2 }),
  },
  {
    id: 'dart',
    name: 'Dart',
    category: 'arms',
    encumbranceGp: 5,
    valueGp: toGp({ cp: 3 }),
  },
  {
    id: 'fauchard',
    name: 'Fauchard',
    category: 'arms',
    encumbranceGp: 60,
    valueGp: toGp({ gp: 3 }),
  },
  {
    id: 'fauchard-fork',
    name: 'Fauchard-Fork',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 8 }),
  },
  {
    id: 'flail-footman',
    name: "Flail, footman's",
    category: 'arms',
    encumbranceGp: 150,
    valueGp: toGp({ gp: 3 }),
  },
  {
    id: 'flail-horseman',
    name: "Flail, horseman's",
    category: 'arms',
    encumbranceGp: 35,
    valueGp: toGp({ gp: 8 }),
  },
  {
    id: 'fork-military',
    name: 'Fork, Military',
    category: 'arms',
    encumbranceGp: 75,
    valueGp: toGp({ gp: 4 }),
  },
  {
    id: 'glaive',
    name: 'Glaive',
    category: 'arms',
    encumbranceGp: 75,
    valueGp: toGp({ gp: 6 }),
  },
  {
    id: 'glaive-guisarme',
    name: 'Glaive-Guisarme',
    category: 'arms',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'guisarme',
    name: 'Guisarme',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 5 }),
  },
  {
    id: 'guisarme-voulge',
    name: 'Guisarme-Voulge',
    category: 'arms',
    encumbranceGp: 150,
    valueGp: toGp({ gp: 7 }),
  },
  {
    id: 'halberd',
    name: 'Halberd',
    category: 'arms',
    encumbranceGp: 175,
    valueGp: toGp({ gp: 9 }),
  },
  {
    id: 'hammer-lucern',
    name: 'Hammer, Lucern',
    category: 'arms',
    encumbranceGp: 150,
    valueGp: toGp({ gp: 7 }),
  },
  {
    id: 'hammer',
    name: 'Hammer',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'javelin',
    name: 'Javelin',
    category: 'arms',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 10 }),
  },
  {
    id: 'mace',
    name: "Mace, footman's",
    category: 'arms',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 8 }),
  },
  {
    id: 'mace-horseman',
    name: "Mace, horseman's",
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 4 }),
  },
  {
    id: 'morning-star',
    name: 'Morning Star',
    category: 'arms',
    encumbranceGp: 125,
    valueGp: toGp({ gp: 5 }),
  },
  {
    id: 'partisan',
    name: 'Partisan',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'pick-military-footman',
    name: "Pick, Military, footman's",
    category: 'arms',
    encumbranceGp: 60,
    valueGp: toGp({ gp: 8 }),
  },
  {
    id: 'pick-military-horseman',
    name: "Pick, Military, horseman's",
    category: 'arms',
    encumbranceGp: 40,
    valueGp: toGp({ gp: 5 }),
  },
  {
    id: 'pike-awl',
    name: 'Pike, awl',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 3 }),
  },
  {
    id: 'ranseur',
    name: 'Ranseur',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 4 }),
  },
  {
    id: 'scimitar',
    name: 'Scimitar',
    category: 'arms',
    encumbranceGp: 40,
    valueGp: toGp({ gp: 15 }),
  },
  // House rule: the PHB prices imply a 9 sp sling, but no explicit AD&D encumbrance entry is given.
  {
    id: 'sling',
    name: 'Sling',
    category: 'arms',
    encumbranceGp: 5,
    valueGp: toGp({ sp: 9 }),
  },
  {
    id: 'sling-bullet',
    name: 'Sling bullet',
    category: 'arms',
    encumbranceGp: 2,
    valueGp: toGp({ sp: 0.5 }),
  },
  {
    id: 'spear',
    name: 'Spear',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'spetum',
    name: 'Spetum',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 3 }),
  },
  {
    id: 'staff-quarter',
    name: 'Staff, Quarter',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ sp: 1 }),
  },
  {
    id: 'sword-bastard',
    name: 'Sword, Bastard',
    category: 'arms',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 25 }),
  },
  {
    id: 'sword-broad',
    name: 'Sword, Broad',
    category: 'arms',
    encumbranceGp: 75,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'sword-long',
    name: 'Sword, Long',
    category: 'arms',
    encumbranceGp: 60,
    valueGp: toGp({ gp: 15 }),
  },
  {
    id: 'sword-short',
    name: 'Sword, Short',
    category: 'arms',
    encumbranceGp: 35,
    valueGp: toGp({ gp: 8 }),
  },
  {
    id: 'sword-two-handed',
    name: 'Sword, Two-handed',
    category: 'arms',
    encumbranceGp: 250,
    valueGp: toGp({ gp: 30 }),
  },
  {
    id: 'trident',
    name: 'Trident',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 4 }),
  },
  {
    id: 'voulge',
    name: 'Voulge',
    category: 'arms',
    encumbranceGp: 125,
    valueGp: toGp({ gp: 2 }),
  },
  {
    id: 'bow-composite-long',
    name: 'Bow, composite long',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 100 }),
  },
  {
    id: 'bow-composite-short',
    name: 'Bow, composite short',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 75 }),
  },
  {
    id: 'bow-long',
    name: 'Bow, long',
    category: 'arms',
    encumbranceGp: 100,
    valueGp: toGp({ gp: 60 }),
  },
  {
    id: 'bow-short',
    name: 'Bow, short',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 15 }),
  },
  {
    id: 'crossbow-heavy',
    name: 'Crossbow, heavy',
    category: 'arms',
    encumbranceGp: 80,
    valueGp: toGp({ gp: 20 }),
  },
  {
    id: 'crossbow-light',
    name: 'Crossbow, light',
    category: 'arms',
    encumbranceGp: 50,
    valueGp: toGp({ gp: 12 }),
  },
  {
    id: 'arrow',
    name: 'Arrow, normal, single',
    category: 'arms',
    encumbranceGp: 2,
    valueGp: toGp({ sp: 2 }),
    ammoKind: 'arrow',
  },
  // Questionable: PHB lists more specific quarrel/bolt entries; this is a generic single-bolt convenience entry.
  {
    id: 'bolt',
    name: 'Quarrel or bolt, light, single',
    category: 'arms',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 1 }),
    ammoKind: 'bolt',
  },
  {
    id: 'belt',
    name: 'Belt',
    category: 'clothing',
    encumbranceGp: 3,
    valueGp: toGp({ sp: 3 }),
  },
  {
    id: 'boots-high-hard',
    name: 'Boots, high, hard',
    category: 'clothing',
    encumbranceGp: 60,
    valueGp: toGp({ gp: 2 }),
  },
  {
    id: 'boots-high-soft',
    name: 'Boots, high, soft',
    category: 'clothing',
    encumbranceGp: 30,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'boots-low-hard',
    name: 'Boots, low, hard',
    category: 'clothing',
    encumbranceGp: 60,
    valueGp: toGp({ sp: 9 }),
  },
  {
    id: 'boots-low-soft',
    name: 'Boots, low, soft',
    category: 'clothing',
    encumbranceGp: 30,
    valueGp: toGp({ sp: 8 }),
  },
  // Inferred from nearby DMG clothing entries; small worn item.
  {
    id: 'cap',
    name: 'Cap',
    category: 'clothing',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 1 }),
  },
  // Inferred from nearby DMG clothing entries; small worn item.
  {
    id: 'hat',
    name: 'Hat',
    category: 'clothing',
    encumbranceGp: 2,
    valueGp: toGp({ sp: 7 }),
  },
  {
    id: 'cloak',
    name: 'Cloak',
    category: 'clothing',
    encumbranceGp: 25,
    valueGp: toGp({ sp: 5 }),
  },
  // Inferred from belt vs. broader worn clothing.
  {
    id: 'girdle-broad',
    name: 'Girdle, broad',
    category: 'clothing',
    encumbranceGp: 5,
    valueGp: toGp({ gp: 2 }),
  },
  // Inferred from belt.
  {
    id: 'girdle-normal',
    name: 'Girdle, normal',
    category: 'clothing',
    encumbranceGp: 3,
    valueGp: toGp({ sp: 10 }),
  },
  {
    id: 'robe',
    name: 'Robe',
    category: 'clothing',
    encumbranceGp: 25,
    valueGp: toGp({ sp: 6 }),
  },
  // Inferred from the DMG note that very small carried items have negligible but non-zero bulk.
  {
    id: 'belladonna-sprig',
    name: 'Belladonna, sprig',
    category: 'herbs',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 4 }),
  },
  // Inferred from the DMG note that very small carried items have negligible but non-zero bulk.
  {
    id: 'garlic-bud',
    name: 'Garlic, bud',
    category: 'herbs',
    encumbranceGp: 1,
    valueGp: toGp({ cp: 5 }),
  },
  // Inferred from the DMG note that very small carried items have negligible but non-zero bulk.
  {
    id: 'wolvesbane-sprig',
    name: 'Wolvesbane, sprig',
    category: 'herbs',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 10 }),
  },
  // Questionable: modeled split of the PHB's single "Skin for water or wine" item.
  {
    id: 'waterskin-empty',
    name: 'Skin for water or wine (empty)',
    category: 'adventuring-gear',
    encumbranceGp: 5,
    valueGp: toGp({ sp: 15 }),
  },
  // Questionable: modeled split of the PHB's single "Skin for water or wine" item.
  {
    id: 'waterskin-full',
    name: 'Skin for water or wine (full)',
    category: 'adventuring-gear',
    encumbranceGp: 50,
    valueGp: toGp({ sp: 15 }),
  },
  {
    id: 'scroll-case-leather',
    name: 'Case, leather, map or scroll',
    category: 'adventuring-gear',
    encumbranceGp: 25,
    valueGp: toGp({ sp: 15 }),
  },
  {
    id: 'scroll-case-bone',
    name: 'Case, bone, map or scroll',
    category: 'adventuring-gear',
    encumbranceGp: 50,
    valueGp: toGp({ sp: 5 }),
  },
  {
    id: 'candle',
    name: 'Candle, wax',
    category: 'adventuring-gear',
    encumbranceGp: 5,
    valueGp: toGp({ sp: 1 }),
  },
  {
    id: 'candle-tallow',
    name: 'Candle, tallow',
    category: 'adventuring-gear',
    encumbranceGp: 5,
    valueGp: toGp({ cp: 1 }),
  },
  {
    id: 'torch',
    name: 'Torch',
    category: 'adventuring-gear',
    encumbranceGp: 25,
    valueGp: toGp({ cp: 1 }),
  },
  {
    id: 'rope-50',
    name: "Rope, 50'",
    category: 'adventuring-gear',
    encumbranceGp: 75,
    valueGp: toGp({ sp: 4 }),
  },
  {
    id: 'tinderbox',
    name: 'Tinder Box, with flint & steel',
    category: 'adventuring-gear',
    encumbranceGp: 2,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'lantern',
    name: 'Lantern, hooded',
    category: 'adventuring-gear',
    encumbranceGp: 60,
    valueGp: toGp({ sp: 7 }),
  },
  {
    id: 'lantern-bullseye',
    name: 'Lantern, bullseye',
    category: 'adventuring-gear',
    encumbranceGp: 60,
    valueGp: toGp({ gp: 12 }),
  },
  // Questionable: not a literal PHB reference-sheet row; kept as a modeled utility item.
  {
    id: 'flask-empty',
    name: 'Flask, empty',
    category: 'adventuring-gear',
    encumbranceGp: 7,
    valueGp: toGp({ cp: 3 }),
  },
  {
    id: 'oil-flask',
    name: 'Oil, flask of',
    category: 'adventuring-gear',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 1 }),
  },
  {
    id: 'holy-water',
    name: 'Water, Holy, vial',
    category: 'religious-items',
    encumbranceGp: 25,
    valueGp: toGp({ gp: 25 }),
  },
  // Questionable: modeled counterpart, not a PHB reference-sheet row.
  {
    id: 'unholy-water',
    name: 'Water, Unholy, vial',
    category: 'religious-items',
    encumbranceGp: 25,
    valueGp: toGp({ gp: 25 }),
  },
  // Inferred as a very small carried devotional item.
  {
    id: 'beads-prayer',
    name: 'Beads, Prayer',
    category: 'religious-items',
    encumbranceGp: 1,
    valueGp: toGp({ gp: 1 }),
  },
  // Inferred as a very small carried devotional item.
  {
    id: 'incense-stick',
    name: 'Incense, stick',
    category: 'religious-items',
    encumbranceGp: 1,
    valueGp: toGp({ gp: 1 }),
  },
  // Questionable: modeled convenience entry; the PHB reference sheet lists iron and silver holy symbols.
  {
    id: 'holy-symbol-wood',
    name: 'Symbol, Holy, wooden',
    category: 'religious-items',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 7 }),
  },
  // Inferred as a small worn religious item.
  {
    id: 'holy-symbol-iron',
    name: 'Symbol, Holy, iron',
    category: 'religious-items',
    encumbranceGp: 20,
    valueGp: toGp({ gp: 2 }),
  },
  // Inferred as a small worn religious item.
  {
    id: 'holy-symbol-silver',
    name: 'Symbol, Holy, silver',
    category: 'religious-items',
    encumbranceGp: 20,
    valueGp: toGp({ gp: 50 }),
  },
  // Inferred from a filled flask-sized liquid container.
  {
    id: 'ale-pint',
    name: 'Ale, pint',
    category: 'provisions',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 1 }),
  },
  // Inferred from a filled flask-sized liquid container.
  {
    id: 'beer-pint',
    name: 'Beer, small, pint',
    category: 'provisions',
    encumbranceGp: 20,
    valueGp: toGp({ cp: 5 }),
  },
  // Inferred from a filled flask-sized liquid container.
  {
    id: 'mead-pint',
    name: 'Mead, pint',
    category: 'provisions',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 5 }),
  },
  {
    id: 'rations-standard',
    name: 'Rations, standard (1 week)',
    category: 'provisions',
    encumbranceGp: 200,
    valueGp: toGp({ gp: 3 }),
  },
  {
    id: 'rations-iron',
    name: 'Rations, iron (1 week)',
    category: 'provisions',
    encumbranceGp: 75,
    valueGp: toGp({ gp: 5 }),
  },
  // Inferred from a filled flask-sized liquid container.
  {
    id: 'wine-good-pint',
    name: 'Wine, pint, good',
    category: 'provisions',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 10 }),
  },
  // Inferred from a filled flask-sized liquid container.
  {
    id: 'wine-watered-pint',
    name: 'Wine, pint, watered',
    category: 'provisions',
    encumbranceGp: 20,
    valueGp: toGp({ sp: 5 }),
  },
  {
    id: 'spike',
    name: 'Spike, iron, large',
    category: 'adventuring-gear',
    encumbranceGp: 10,
    valueGp: toGp({ cp: 1 }),
  },
  {
    id: 'mirror',
    name: 'Mirror, small, silver',
    category: 'adventuring-gear',
    encumbranceGp: 5,
    valueGp: toGp({ gp: 20 }),
  },
  {
    id: 'mirror-large-metal',
    name: 'Mirror, large metal',
    category: 'adventuring-gear',
    encumbranceGp: 5,
    valueGp: toGp({ gp: 10 }),
  },
  {
    id: 'pole-10',
    name: "Pole, 10'",
    category: 'adventuring-gear',
    encumbranceGp: 100,
    valueGp: toGp({ cp: 3 }),
  },
  // Appendix P explicitly treats thieves' picks and tools as non-encumbering standard kit.
  {
    id: 'thieves-picks-tools',
    name: "Thieves' picks & tools",
    category: 'adventuring-gear',
    encumbranceGp: 0,
    valueGp: toGp({ gp: 30 }),
  },
  // Questionable: user-requested treasure entry, not a PHB equipment-table row.
  {
    id: 'diamond',
    name: 'Diamond',
    category: 'treasure',
    encumbranceGp: 1,
    valueGp: toGp({ gp: 100 }),
  },
  // Questionable: user-requested treasure entry, not a PHB equipment-table row.
  {
    id: 'emerald',
    name: 'Emerald',
    category: 'treasure',
    encumbranceGp: 1,
    valueGp: toGp({ gp: 500 }),
  },
  {
    id: 'coin-copper',
    name: 'Copper piece',
    category: 'coins',
    encumbranceGp: 1,
    valueGp: toGp({ cp: 1 }),
  },
  {
    id: 'coin-silver',
    name: 'Silver piece',
    category: 'coins',
    encumbranceGp: 1,
    valueGp: toGp({ sp: 1 }),
  },
  {
    id: 'coin-electrum',
    name: 'Electrum piece',
    category: 'coins',
    encumbranceGp: 1,
    valueGp: toGp({ ep: 1 }),
  },
  {
    id: 'coin-gold',
    name: 'Gold piece',
    category: 'coins',
    encumbranceGp: 1,
    valueGp: toGp({ gp: 1 }),
  },
  {
    id: 'coin-platinum',
    name: 'Platinum piece',
    category: 'coins',
    encumbranceGp: 1,
    valueGp: toGp({ pp: 1 }),
  },
];

export const encumbranceCatalogById = new Map(
  encumbranceCatalog.map((item) => [item.id, item])
);
