import type { EncumbranceCatalogItem } from '../types/encumbrance';

export const encumbranceCatalog: EncumbranceCatalogItem[] = [
  {
    id: 'backpack',
    name: 'Backpack',
    category: 'containers',
    encumbranceGp: 20,
    isContainer: true,
    capacityGp: 300,
  },
  {
    id: 'belt',
    name: 'Belt',
    category: 'gear',
    encumbranceGp: 3,
  },
  {
    id: 'belt-pouch-small',
    name: 'Belt pouch, small',
    category: 'containers',
    encumbranceGp: 5,
    isContainer: true,
    capacityGp: 25,
  },
  {
    id: 'belt-pouch-large',
    name: 'Belt pouch, large',
    category: 'containers',
    encumbranceGp: 10,
    isContainer: true,
    capacityGp: 50,
  },
  {
    id: 'purse',
    name: 'Purse',
    category: 'containers',
    encumbranceGp: 1,
    isContainer: true,
    capacityGp: 25,
  },
  {
    id: 'sack-small',
    name: 'Sack, small',
    category: 'containers',
    encumbranceGp: 5,
    isContainer: true,
    capacityGp: 100,
  },
  {
    id: 'sack-large',
    name: 'Sack, large',
    category: 'containers',
    encumbranceGp: 20,
    isContainer: true,
    capacityGp: 400,
  },
  {
    id: 'quiver-arrows-12',
    name: 'Quiver (12 arrows)',
    category: 'containers',
    encumbranceGp: 30,
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'arrow',
      quantity: 12,
    },
  },
  {
    id: 'quiver-arrows-20',
    name: 'Quiver (20 arrows)',
    category: 'containers',
    encumbranceGp: 30,
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'arrow',
      quantity: 20,
    },
  },
  {
    id: 'quiver-bolts-20',
    name: 'Quiver (20 bolts)',
    category: 'containers',
    encumbranceGp: 30,
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'bolt',
      quantity: 20,
    },
  },
  {
    id: 'quiver-bolts-40',
    name: 'Quiver (40 bolts)',
    category: 'containers',
    encumbranceGp: 30,
    isContainer: true,
    ammoCapacity: {
      ammoKind: 'bolt',
      quantity: 40,
    },
  },
  {
    id: 'waterskin-empty',
    name: 'Waterskin or wineskin (empty)',
    category: 'gear',
    encumbranceGp: 5,
  },
  {
    id: 'waterskin-full',
    name: 'Waterskin or wineskin (full)',
    category: 'gear',
    encumbranceGp: 50,
  },
  {
    id: 'scroll-case-leather',
    name: 'Scroll case, leather',
    category: 'gear',
    encumbranceGp: 25,
  },
  {
    id: 'scroll-case-bone',
    name: 'Scroll case, bone or ivory',
    category: 'gear',
    encumbranceGp: 50,
  },
  {
    id: 'torch',
    name: 'Torch',
    category: 'gear',
    encumbranceGp: 25,
  },
  {
    id: 'candle',
    name: 'Candle',
    category: 'gear',
    encumbranceGp: 5,
  },
  {
    id: 'rope-50',
    name: "Rope, 50'",
    category: 'gear',
    encumbranceGp: 75,
  },
  {
    id: 'grapnel',
    name: 'Grapnel',
    category: 'gear',
    encumbranceGp: 100,
  },
  {
    id: 'tinderbox',
    name: 'Tinderbox',
    category: 'gear',
    encumbranceGp: 2,
  },
  {
    id: 'lantern',
    name: 'Lantern',
    category: 'gear',
    encumbranceGp: 60,
  },
  {
    id: 'flask-empty',
    name: 'Flask, empty',
    category: 'gear',
    encumbranceGp: 7,
  },
  {
    id: 'oil-flask',
    name: 'Flask of oil',
    category: 'gear',
    encumbranceGp: 20,
  },
  {
    id: 'holy-water',
    name: 'Holy water, potion bottle',
    category: 'gear',
    encumbranceGp: 25,
  },
  {
    id: 'rations-standard',
    name: 'Rations, standard (1 week)',
    category: 'provisions',
    encumbranceGp: 200,
  },
  {
    id: 'rations-iron',
    name: 'Rations, iron (1 week)',
    category: 'provisions',
    encumbranceGp: 75,
  },
  {
    id: 'spike',
    name: 'Spike',
    category: 'gear',
    encumbranceGp: 10,
  },
  {
    id: 'mirror',
    name: 'Mirror',
    category: 'gear',
    encumbranceGp: 5,
  },
  {
    id: 'pole-10',
    name: "Pole, 10'",
    category: 'gear',
    encumbranceGp: 100,
  },
  {
    id: 'caltrop',
    name: 'Caltrop',
    category: 'gear',
    encumbranceGp: 50,
  },
  {
    id: 'arrow',
    name: 'Arrow',
    category: 'ammunition',
    encumbranceGp: 2,
    ammoKind: 'arrow',
  },
  {
    id: 'bolt',
    name: 'Crossbow bolt',
    category: 'ammunition',
    encumbranceGp: 1,
    ammoKind: 'bolt',
  },
  {
    id: 'axe-battle',
    name: 'Axe, Battle',
    category: 'weapons',
    encumbranceGp: 75,
  },
  {
    id: 'axe-hand',
    name: 'Axe, Hand',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'club',
    name: 'Club',
    category: 'weapons',
    encumbranceGp: 30,
  },
  {
    id: 'dagger',
    name: 'Dagger',
    category: 'weapons',
    encumbranceGp: 10,
  },
  {
    id: 'dart',
    name: 'Dart',
    category: 'weapons',
    encumbranceGp: 5,
  },
  {
    id: 'javelin',
    name: 'Javelin',
    category: 'weapons',
    encumbranceGp: 20,
  },
  {
    id: 'mace',
    name: "Mace, footman's",
    category: 'weapons',
    encumbranceGp: 100,
  },
  {
    id: 'spear',
    name: 'Spear',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'staff-quarter',
    name: 'Staff, Quarter',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'sword-bastard',
    name: 'Sword, Bastard',
    category: 'weapons',
    encumbranceGp: 100,
  },
  {
    id: 'sword-broad',
    name: 'Sword, Broad',
    category: 'weapons',
    encumbranceGp: 75,
  },
  {
    id: 'sword-long',
    name: 'Sword, Long',
    category: 'weapons',
    encumbranceGp: 60,
  },
  {
    id: 'sword-short',
    name: 'Sword, Short',
    category: 'weapons',
    encumbranceGp: 35,
  },
  {
    id: 'sword-two-handed',
    name: 'Sword, Two-handed',
    category: 'weapons',
    encumbranceGp: 250,
  },
  {
    id: 'bow-composite-long',
    name: 'Bow, composite long',
    category: 'weapons',
    encumbranceGp: 80,
  },
  {
    id: 'bow-composite-short',
    name: 'Bow, composite short',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'bow-long',
    name: 'Bow, long',
    category: 'weapons',
    encumbranceGp: 100,
  },
  {
    id: 'bow-short',
    name: 'Bow, short',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'crossbow-heavy',
    name: 'Crossbow, heavy',
    category: 'weapons',
    encumbranceGp: 80,
  },
  {
    id: 'crossbow-light',
    name: 'Crossbow, light',
    category: 'weapons',
    encumbranceGp: 50,
  },
  {
    id: 'armor-leather',
    name: 'Leather armor',
    category: 'armor',
    encumbranceGp: 150,
  },
  {
    id: 'armor-padded',
    name: 'Padded armor',
    category: 'armor',
    encumbranceGp: 100,
  },
  {
    id: 'armor-ring',
    name: 'Ring mail',
    category: 'armor',
    encumbranceGp: 250,
  },
  {
    id: 'armor-studded',
    name: 'Studded leather',
    category: 'armor',
    encumbranceGp: 200,
  },
  {
    id: 'armor-scale',
    name: 'Scale mail',
    category: 'armor',
    encumbranceGp: 400,
  },
  {
    id: 'armor-chain',
    name: 'Chain mail',
    category: 'armor',
    encumbranceGp: 300,
  },
  {
    id: 'armor-splint',
    name: 'Splint mail',
    category: 'armor',
    encumbranceGp: 400,
  },
  {
    id: 'armor-banded',
    name: 'Banded mail',
    category: 'armor',
    encumbranceGp: 350,
  },
  {
    id: 'armor-plate',
    name: 'Plate mail',
    category: 'armor',
    encumbranceGp: 450,
  },
  {
    id: 'shield-small',
    name: 'Shield, small',
    category: 'armor',
    encumbranceGp: 50,
  },
  {
    id: 'shield-small-wood',
    name: 'Shield, small, wood',
    category: 'armor',
    encumbranceGp: 30,
  },
  {
    id: 'shield-large',
    name: 'Shield, large',
    category: 'armor',
    encumbranceGp: 100,
  },
  {
    id: 'coin-copper',
    name: 'Copper piece',
    category: 'coins',
    encumbranceGp: 1,
  },
  {
    id: 'coin-silver',
    name: 'Silver piece',
    category: 'coins',
    encumbranceGp: 1,
  },
  {
    id: 'coin-electrum',
    name: 'Electrum piece',
    category: 'coins',
    encumbranceGp: 1,
  },
  {
    id: 'coin-gold',
    name: 'Gold piece',
    category: 'coins',
    encumbranceGp: 1,
  },
  {
    id: 'coin-platinum',
    name: 'Platinum piece',
    category: 'coins',
    encumbranceGp: 1,
  },
];

export const encumbranceCatalogById = new Map(
  encumbranceCatalog.map((item) => [item.id, item])
);
