import {
  HAZARD_CHILD_POST_PROCESSORS,
  HAZARD_PENDING_RESOLVERS,
  HAZARD_PREVIEW_FACTORIES,
  HAZARD_REGISTRY_OUTCOMES,
  HAZARD_RENDER_ADAPTERS,
  HAZARD_TABLE_DEFINITIONS,
} from '.';

export type HazardTableId =
  typeof HAZARD_TABLE_DEFINITIONS[number]['id'];

export const HAZARD_TABLE_ID_LIST: ReadonlyArray<HazardTableId> =
  HAZARD_TABLE_DEFINITIONS.map((def) => def.id);

export const HAZARD_TABLE_HEADINGS = Object.fromEntries(
  HAZARD_TABLE_DEFINITIONS.map((def) => [def.id, def.heading])
) as Record<HazardTableId, string>;

export {
  HAZARD_CHILD_POST_PROCESSORS,
  HAZARD_PENDING_RESOLVERS,
  HAZARD_PREVIEW_FACTORIES,
  HAZARD_REGISTRY_OUTCOMES,
  HAZARD_RENDER_ADAPTERS,
  HAZARD_TABLE_DEFINITIONS,
};
