import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum TreasureArmorShield {
  ChainMailPlus1,
  ChainMailPlus2,
  ChainMailPlus3,
  LeatherArmorPlus1,
  PlateMailPlus1,
  PlateMailPlus2,
  PlateMailPlus3,
  PlateMailPlus4,
  PlateMailPlus5,
  PlateMailOfEtherealness,
  PlateMailOfVulnerability,
  RingMailPlus1,
  ScaleMailPlus1,
  ScaleMailPlus2,
  SplintMailPlus1,
  SplintMailPlus2,
  SplintMailPlus3,
  SplintMailPlus4,
  StuddedLeatherPlus1,
  ShieldPlus1,
  ShieldPlus2,
  ShieldPlus3,
  ShieldPlus4,
  ShieldPlus5,
  ShieldLargePlus1Plus4VsMissiles,
  ShieldMinus1MissileAttractor,
}

export const treasureArmorShields: Table<TreasureArmorShield> = {
  sides: 100,
  entries: [
    { range: [1, 5], command: TreasureArmorShield.ChainMailPlus1 },
    { range: [6, 9], command: TreasureArmorShield.ChainMailPlus2 },
    { range: [10, 11], command: TreasureArmorShield.ChainMailPlus3 },
    { range: [12, 19], command: TreasureArmorShield.LeatherArmorPlus1 },
    { range: [20, 26], command: TreasureArmorShield.PlateMailPlus1 },
    { range: [27, 32], command: TreasureArmorShield.PlateMailPlus2 },
    { range: [33, 35], command: TreasureArmorShield.PlateMailPlus3 },
    { range: [36, 37], command: TreasureArmorShield.PlateMailPlus4 },
    { range: [38], command: TreasureArmorShield.PlateMailPlus5 },
    { range: [39], command: TreasureArmorShield.PlateMailOfEtherealness },
    { range: [40, 44], command: TreasureArmorShield.PlateMailOfVulnerability },
    { range: [45, 50], command: TreasureArmorShield.RingMailPlus1 },
    { range: [51, 55], command: TreasureArmorShield.ScaleMailPlus1 },
    { range: [56, 59], command: TreasureArmorShield.ScaleMailPlus2 },
    { range: [60, 63], command: TreasureArmorShield.SplintMailPlus1 },
    { range: [64, 66], command: TreasureArmorShield.SplintMailPlus2 },
    { range: [67, 68], command: TreasureArmorShield.SplintMailPlus3 },
    { range: [69], command: TreasureArmorShield.SplintMailPlus4 },
    { range: [70, 75], command: TreasureArmorShield.StuddedLeatherPlus1 },
    { range: [76, 84], command: TreasureArmorShield.ShieldPlus1 },
    { range: [85, 89], command: TreasureArmorShield.ShieldPlus2 },
    { range: [90, 93], command: TreasureArmorShield.ShieldPlus3 },
    { range: [94, 95], command: TreasureArmorShield.ShieldPlus4 },
    { range: [96], command: TreasureArmorShield.ShieldPlus5 },
    {
      range: [97],
      command: TreasureArmorShield.ShieldLargePlus1Plus4VsMissiles,
    },
    {
      range: [98, 100],
      command: TreasureArmorShield.ShieldMinus1MissileAttractor,
    },
  ],
};
