export const BASE_TABLE_ID_LIST = [
  'roomDimensions',
  'chamberDimensions',
  'chamberRoomContents',
  'chamberRoomStairs',
  'unusualShape',
  'unusualSize',
  'treasure',
  'treasureArmorShields',
  'treasureSwords',
  'treasureSwordKind',
  'treasureSwordUnusual',
  'treasureSwordPrimaryAbility',
  'treasureSwordPrimaryAbilityRestricted',
  'treasureSwordExtraordinaryPower',
  'treasureSwordExtraordinaryPowerRestricted',
  'treasureSwordDragonSlayerColor',
  'treasureSwordSpecialPurpose',
  'treasureSwordSpecialPurposePower',
  'treasureSwordAlignment',
  'treasureSwordAlignmentChaotic',
  'treasureSwordAlignmentLawful',
  'treasureMiscWeapons',
  'circularContents',
  'circularPool',
  'circularMagicPool',
  'transmuteType',
  'poolAlignment',
  'transporterLocation',
] as const;

export type BaseTableId = typeof BASE_TABLE_ID_LIST[number];

export const BASE_TABLE_HEADINGS: Record<BaseTableId, string> = {
  roomDimensions: 'Room Dimensions',
  chamberDimensions: 'Chamber Dimensions',
  chamberRoomContents: 'Contents',
  chamberRoomStairs: 'Stairway',
  unusualShape: 'Unusual Shape',
  unusualSize: 'Unusual Size',
  treasure: 'Treasure',
  treasureArmorShields: 'Armor & Shields (Table F)',
  treasureSwords: 'Swords (Table G)',
  treasureSwordKind: 'Sword Type',
  treasureSwordUnusual: 'Sword Unusual Traits',
  treasureSwordPrimaryAbility: 'Primary Ability',
  treasureSwordPrimaryAbilityRestricted: 'Primary Ability (01-92)',
  treasureSwordExtraordinaryPower: 'Extraordinary Power',
  treasureSwordExtraordinaryPowerRestricted: 'Extraordinary Power (01-97)',
  treasureSwordDragonSlayerColor: 'Dragon Slayer Target',
  treasureSwordSpecialPurpose: 'Sword Special Purpose',
  treasureSwordSpecialPurposePower: 'Sword Special Purpose Power',
  treasureSwordAlignment: 'Sword Alignment',
  treasureSwordAlignmentChaotic: 'Sword Alignment (Chaotic)',
  treasureSwordAlignmentLawful: 'Sword Alignment (Lawful)',
  treasureMiscWeapons: 'Miscellaneous Weapons (Table H)',
  circularContents: 'Circular Contents',
  circularPool: 'Pool',
  circularMagicPool: 'Magic Pool Effect',
  transmuteType: 'Transmutation Type',
  poolAlignment: 'Pool Alignment',
  transporterLocation: 'Transporter Location',
};
