export const BASE_TABLE_ID_LIST = [
  'monsterTen',
  'dragonTen',
  'human',
  'roomDimensions',
  'chamberDimensions',
  'chamberRoomContents',
  'chamberRoomStairs',
  'unusualShape',
  'unusualSize',
  'treasure',
  'treasureMiscMagicE4',
  'treasureMiscMagicE5',
  'treasureArmorShields',
  'treasureSwords',
  'treasureSwordKind',
  'treasureSwordUnusual',
  'treasureSwordPrimaryAbility',
  'treasureSwordPrimaryAbilityRestricted',
  'treasureSwordExtraordinaryPower',
  'treasureSwordExtraordinaryPowerRestricted',
  'treasureSwordDragonSlayerColor',
  'treasureSwordSpecialPurpose',
  'treasureSwordSpecialPurposePower',
  'treasureSwordAlignment',
  'treasureSwordAlignmentChaotic',
  'treasureSwordAlignmentLawful',
  'treasureMiscWeapons',
  'treasureRobeOfUsefulItems',
  'treasureRobeOfTheArchmagi',
  'treasureScarabOfProtectionCurse',
  'treasureScarabOfProtectionCurseResolution',
  'treasureManualOfGolems',
  'treasureMedallionRange',
  'treasureNecklaceOfMissiles',
  'treasurePearlOfPowerEffect',
  'treasurePearlOfPowerRecall',
  'treasurePearlOfWisdom',
  'treasurePeriaptProofAgainstPoison',
  'treasurePhylacteryLongYears',
  'treasureQuaalFeatherToken',
  'circularContents',
  'circularPool',
  'circularMagicPool',
  'transmuteType',
  'poolAlignment',
  'transporterLocation',
] as const;

export type BaseTableId = typeof BASE_TABLE_ID_LIST[number];

export const BASE_TABLE_HEADINGS: Record<BaseTableId, string> = {
  monsterTen: 'Monster (Level 10)',
  dragonTen: 'Dragon (Level 10)',
  human: 'Human Subtable',
  roomDimensions: 'Room Dimensions',
  chamberDimensions: 'Chamber Dimensions',
  chamberRoomContents: 'Contents',
  chamberRoomStairs: 'Stairway',
  unusualShape: 'Unusual Shape',
  unusualSize: 'Unusual Size',
  treasure: 'Treasure',
  treasureMiscMagicE4: 'Miscellaneous Magic (Table E.4)',
  treasureMiscMagicE5: 'Miscellaneous Magic (Table E.5)',
  treasureArmorShields: 'Armor & Shields (Table F)',
  treasureSwords: 'Swords (Table G)',
  treasureSwordKind: 'Sword Type',
  treasureSwordUnusual: 'Sword Unusual Traits',
  treasureSwordPrimaryAbility: 'Primary Ability',
  treasureSwordPrimaryAbilityRestricted: 'Primary Ability (01-92)',
  treasureSwordExtraordinaryPower: 'Extraordinary Power',
  treasureSwordExtraordinaryPowerRestricted: 'Extraordinary Power (01-97)',
  treasureSwordDragonSlayerColor: 'Dragon Slayer Target',
  treasureSwordSpecialPurpose: 'Sword Special Purpose',
  treasureSwordSpecialPurposePower: 'Sword Special Purpose Power',
  treasureSwordAlignment: 'Sword Alignment',
  treasureSwordAlignmentChaotic: 'Sword Alignment (Chaotic)',
  treasureSwordAlignmentLawful: 'Sword Alignment (Lawful)',
  treasureMiscWeapons: 'Miscellaneous Weapons (Table H)',
  treasureRobeOfUsefulItems: 'Robe of Useful Items',
  treasureRobeOfTheArchmagi: 'Robe of the Archmagi Alignment',
  treasureScarabOfProtectionCurse: 'Scarab of Protection (curse check)',
  treasureScarabOfProtectionCurseResolution:
    'Scarab of Protection (curse resolution)',
  treasureManualOfGolems: 'Manual of Golems',
  treasureMedallionRange: 'Medallion Details',
  treasureNecklaceOfMissiles: 'Necklace of Missiles',
  treasurePearlOfPowerEffect: 'Pearl of Power Effect',
  treasurePearlOfPowerRecall: 'Pearl of Power Recall',
  treasurePearlOfWisdom: 'Pearl of Wisdom Outcome',
  treasurePeriaptProofAgainstPoison: 'Periapt of Proof Against Poison',
  treasurePhylacteryLongYears: 'Phylactery of Long Years',
  treasureQuaalFeatherToken: "Quaal's Feather Token",
  circularContents: 'Circular Contents',
  circularPool: 'Pool',
  circularMagicPool: 'Magic Pool Effect',
  transmuteType: 'Transmutation Type',
  poolAlignment: 'Pool Alignment',
  transporterLocation: 'Transporter Location',
};
