export const BASE_TABLE_ID_LIST = [
  'monsterLevel',
  'monsterOne',
  'monsterTwo',
  'monsterThree',
  'monsterFour',
  'monsterFive',
  'monsterSix',
  'monsterSeven',
  'monsterEight',
  'monsterNine',
  'monsterTen',
  'dragonThree',
  'dragonFourYounger',
  'dragonFourOlder',
  'dragonFiveYounger',
  'dragonFiveOlder',
  'dragonSix',
  'dragonSeven',
  'dragonEight',
  'dragonNine',
  'dragonTen',
  'human',
  'roomDimensions',
  'chamberDimensions',
  'chamberRoomContents',
  'chamberRoomStairs',
  'unusualShape',
  'unusualSize',
  'treasure',
  'treasureContainer',
  'treasureProtectionType',
  'treasureProtectionGuardedBy',
  'treasureProtectionHiddenBy',
  'treasureMiscMagicE2',
  'treasureMiscMagicE3',
  'treasureMiscMagicE4',
  'treasureMiscMagicE5',
  'treasureArmorShields',
  'treasureSwords',
  'treasureSwordKind',
  'treasureSwordUnusual',
  'treasureSwordPrimaryAbility',
  'treasureSwordPrimaryAbilityRestricted',
  'treasureSwordExtraordinaryPower',
  'treasureSwordExtraordinaryPowerRestricted',
  'treasureSwordDragonSlayerColor',
  'treasureSwordSpecialPurpose',
  'treasureSwordSpecialPurposePower',
  'treasureSwordAlignment',
  'treasureSwordAlignmentChaotic',
  'treasureSwordAlignmentLawful',
  'treasureMiscWeapons',
  'treasureRobeOfUsefulItems',
  'treasureRobeOfTheArchmagi',
  'treasureScarabOfProtectionCurse',
  'treasureScarabOfProtectionCurseResolution',
  'treasureManualOfGolems',
  'treasureMedallionRange',
  'treasureNecklaceOfMissiles',
  'treasurePearlOfPowerEffect',
  'treasurePearlOfPowerRecall',
  'treasurePearlOfWisdom',
  'treasurePeriaptProofAgainstPoison',
  'treasurePhylacteryLongYears',
  'treasureQuaalFeatherToken',
  'treasureFigurineOfWondrousPower',
  'treasureFigurineMarbleElephant',
  'treasureGirdleOfGiantStrength',
  'treasureInstrumentOfTheBards',
  'treasureIronFlask',
  'treasureHornOfValhallaType',
  'treasureHornOfValhallaAttunement',
  'treasureHornOfValhallaAlignment',
  'treasureIounStones',
  'treasureCarpetOfFlying',
  'treasureCloakOfProtection',
  'treasureCrystalBall',
  'treasureDeckOfManyThings',
  'treasureEyesOfPetrification',
  'circularContents',
  'circularPool',
  'circularMagicPool',
  'transmuteType',
  'poolAlignment',
  'transporterLocation',
] as const;

export type BaseTableId = typeof BASE_TABLE_ID_LIST[number];

export const BASE_TABLE_HEADINGS: Record<BaseTableId, string> = {
  monsterLevel: 'Monster Level',
  monsterOne: 'Monster (Level 1)',
  monsterTwo: 'Monster (Level 2)',
  monsterThree: 'Monster (Level 3)',
  monsterFour: 'Monster (Level 4)',
  monsterFive: 'Monster (Level 5)',
  monsterSix: 'Monster (Level 6)',
  monsterSeven: 'Monster (Level 7)',
  monsterEight: 'Monster (Level 8)',
  monsterNine: 'Monster (Level 9)',
  monsterTen: 'Monster (Level 10)',
  dragonThree: 'Dragon (Level 3)',
  dragonFourYounger: 'Dragon (Younger)',
  dragonFourOlder: 'Dragon (Older)',
  dragonFiveYounger: 'Dragon (Younger)',
  dragonFiveOlder: 'Dragon (Older)',
  dragonSix: 'Dragon (Level 6)',
  dragonSeven: 'Dragon (Level 7)',
  dragonEight: 'Dragon (Level 8)',
  dragonNine: 'Dragon (Level 9)',
  dragonTen: 'Dragon (Level 10)',
  human: 'Human Subtable',
  roomDimensions: 'Room Dimensions',
  chamberDimensions: 'Chamber Dimensions',
  chamberRoomContents: 'Contents',
  chamberRoomStairs: 'Stairway',
  unusualShape: 'Unusual Shape',
  unusualSize: 'Unusual Size',
  treasure: 'Treasure',
  treasureContainer: 'Treasure Container',
  treasureProtectionType: 'Treasure Protection',
  treasureProtectionGuardedBy: 'Treasure Guarded By',
  treasureProtectionHiddenBy: 'Treasure Hidden By',
  treasureMiscMagicE2: 'Miscellaneous Magic (Table E.2)',
  treasureMiscMagicE3: 'Miscellaneous Magic (Table E.3)',
  treasureMiscMagicE4: 'Miscellaneous Magic (Table E.4)',
  treasureMiscMagicE5: 'Miscellaneous Magic (Table E.5)',
  treasureArmorShields: 'Armor & Shields (Table F)',
  treasureSwords: 'Swords (Table G)',
  treasureSwordKind: 'Sword Type',
  treasureSwordUnusual: 'Sword Unusual Traits',
  treasureSwordPrimaryAbility: 'Primary Ability',
  treasureSwordPrimaryAbilityRestricted: 'Primary Ability (01-92)',
  treasureSwordExtraordinaryPower: 'Extraordinary Power',
  treasureSwordExtraordinaryPowerRestricted: 'Extraordinary Power (01-97)',
  treasureSwordDragonSlayerColor: 'Dragon Slayer Target',
  treasureSwordSpecialPurpose: 'Sword Special Purpose',
  treasureSwordSpecialPurposePower: 'Sword Special Purpose Power',
  treasureSwordAlignment: 'Sword Alignment',
  treasureSwordAlignmentChaotic: 'Sword Alignment (Chaotic)',
  treasureSwordAlignmentLawful: 'Sword Alignment (Lawful)',
  treasureMiscWeapons: 'Miscellaneous Weapons (Table H)',
  treasureRobeOfUsefulItems: 'Robe of Useful Items',
  treasureRobeOfTheArchmagi: 'Robe of the Archmagi Alignment',
  treasureScarabOfProtectionCurse: 'Scarab of Protection (curse check)',
  treasureScarabOfProtectionCurseResolution:
    'Scarab of Protection (curse resolution)',
  treasureManualOfGolems: 'Manual of Golems',
  treasureMedallionRange: 'Medallion Details',
  treasureNecklaceOfMissiles: 'Necklace of Missiles',
  treasurePearlOfPowerEffect: 'Pearl of Power Effect',
  treasurePearlOfPowerRecall: 'Pearl of Power Recall',
  treasurePearlOfWisdom: 'Pearl of Wisdom Outcome',
  treasurePeriaptProofAgainstPoison: 'Periapt of Proof Against Poison',
  treasurePhylacteryLongYears: 'Phylactery of Long Years',
  treasureQuaalFeatherToken: "Quaal's Feather Token",
  treasureFigurineOfWondrousPower: 'Figurine of Wondrous Power',
  treasureFigurineMarbleElephant: 'Marble Elephant Form',
  treasureGirdleOfGiantStrength: 'Giant Strength Type',
  treasureInstrumentOfTheBards: 'Instrument of the Bards',
  treasureIronFlask: 'Iron Flask Contents',
  treasureHornOfValhallaType: 'Horn Type',
  treasureHornOfValhallaAttunement: 'Attunement',
  treasureHornOfValhallaAlignment: 'Alignment',
  treasureIounStones: 'Ioun Stones',
  treasureCarpetOfFlying: 'Carpet of Flying Size',
  treasureCloakOfProtection: 'Cloak of Protection Bonus',
  treasureCrystalBall: 'Crystal Ball Variant',
  treasureDeckOfManyThings: 'Deck Composition',
  treasureEyesOfPetrification: 'Eyes of Petrification Type',
  circularContents: 'Circular Contents',
  circularPool: 'Pool',
  circularMagicPool: 'Magic Pool Effect',
  transmuteType: 'Transmutation Type',
  poolAlignment: 'Pool Alignment',
  transporterLocation: 'Transporter Location',
};
