import type { Table } from '../../../../tables/dungeon/tableTypes';

export enum MonsterSeven {
  BlackPudding,
  Character,
  Chimera_1to2,
  DemonSuccubus,
  DemonTypeI,
  DemonTypeII,
  DemonTypeIII,
  DevilBarbed,
  DevilBone,
  DevilHorned,
  Dragon,
  Efreeti,
  Elemental,
  Ettin_1to2,
  GiantHillOrStone_1to3,
  GiantFireOrFrost_1to2,
  GolemFlesh,
  Gorgon,
  GroaningSpirit,
  Hydra_10to12Heads,
  HydroPyro_7to9Heads,
  IntellectDevourer,
  InvisibleStalker,
  Lamia_1to2,
  LizardFire_1to3,
  LurkerAbove,
  Mezzodaemon,
  Mimic,
  MindFlayer_1to2,
  Mummy_1to2,
  NagaSpirit_1to2,
  NeoOtyugh,
  NightHag_1to2,
  Roper_1to2,
  ShamblingMound_1to2,
  Shedu_1to2,
  SlugGiant,
  Spectre,
  Trapper,
  UmberHulk,
  WillOWisp_1to3,
  Xorn_1to3,
}

export const monsterSeven: Table<MonsterSeven> = {
  sides: 100,
  entries: [
    { range: [1, 5], command: MonsterSeven.BlackPudding },
    { range: [6, 10], command: MonsterSeven.Character },
    { range: [11, 14], command: MonsterSeven.Chimera_1to2 },
    { range: [15], command: MonsterSeven.DemonSuccubus },
    { range: [16], command: MonsterSeven.DemonTypeI },
    { range: [17], command: MonsterSeven.DemonTypeII },
    { range: [18], command: MonsterSeven.DemonTypeIII },
    { range: [19], command: MonsterSeven.DevilBarbed },
    { range: [20], command: MonsterSeven.DevilBone },
    { range: [21], command: MonsterSeven.DevilHorned },
    { range: [22, 23], command: MonsterSeven.Dragon },
    { range: [24], command: MonsterSeven.Efreeti },
    { range: [25, 26], command: MonsterSeven.Elemental },
    { range: [27, 30], command: MonsterSeven.Ettin_1to2 },
    { range: [31, 35], command: MonsterSeven.GiantHillOrStone_1to3 },
    { range: [36, 38], command: MonsterSeven.GiantFireOrFrost_1to2 },
    { range: [39], command: MonsterSeven.GolemFlesh },
    { range: [40, 41], command: MonsterSeven.Gorgon },
    { range: [42, 43], command: MonsterSeven.GroaningSpirit },
    { range: [44, 46], command: MonsterSeven.Hydra_10to12Heads },
    { range: [47], command: MonsterSeven.HydroPyro_7to9Heads },
    { range: [48, 49], command: MonsterSeven.IntellectDevourer },
    { range: [50], command: MonsterSeven.InvisibleStalker },
    { range: [51, 52], command: MonsterSeven.Lamia_1to2 },
    { range: [53, 56], command: MonsterSeven.LizardFire_1to3 },
    { range: [57, 59], command: MonsterSeven.LurkerAbove },
    { range: [60], command: MonsterSeven.Mezzodaemon },
    { range: [61, 63], command: MonsterSeven.Mimic },
    { range: [64, 65], command: MonsterSeven.MindFlayer_1to2 },
    { range: [66, 69], command: MonsterSeven.Mummy_1to2 },
    { range: [70], command: MonsterSeven.NagaSpirit_1to2 },
    { range: [71, 73], command: MonsterSeven.NeoOtyugh },
    { range: [74], command: MonsterSeven.NightHag_1to2 },
    { range: [75, 78], command: MonsterSeven.Roper_1to2 },
    { range: [79, 82], command: MonsterSeven.ShamblingMound_1to2 },
    { range: [83, 86], command: MonsterSeven.Shedu_1to2 },
    { range: [87], command: MonsterSeven.SlugGiant },
    { range: [88, 91], command: MonsterSeven.Spectre },
    { range: [92, 93], command: MonsterSeven.Trapper },
    { range: [94, 95], command: MonsterSeven.UmberHulk },
    { range: [96, 97], command: MonsterSeven.WillOWisp_1to3 },
    { range: [98, 100], command: MonsterSeven.Xorn_1to3 },
  ],
};

export enum DragonSeven {
  Black_VeryOld_7,
  Blue_Old_6,
  Brass_VeryOld_7,
  Bronze_Old_6,
  Copper_Old_6,
  Gold_Old_6,
  Green_Old_6,
  Red_Old_6,
  Silver_Old_6,
  White_VeryOld_7,
}

export const dragonSeven: Table<DragonSeven> = {
  sides: 100,
  entries: [
    { range: [1, 10], command: DragonSeven.Black_VeryOld_7 },
    { range: [11, 21], command: DragonSeven.Blue_Old_6 },
    { range: [22, 29], command: DragonSeven.Brass_VeryOld_7 },
    { range: [30, 36], command: DragonSeven.Bronze_Old_6 },
    { range: [37, 48], command: DragonSeven.Copper_Old_6 },
    { range: [49, 52], command: DragonSeven.Gold_Old_6 },
    { range: [53, 66], command: DragonSeven.Green_Old_6 },
    { range: [67, 80], command: DragonSeven.Red_Old_6 },
    { range: [81, 87], command: DragonSeven.Silver_Old_6 },
    { range: [88, 100], command: DragonSeven.White_VeryOld_7 },
  ],
};
