import type { Table } from './dungeonTypes';

export enum TreasurePotion {
  AnimalControl,
  Clairaudience,
  Clairvoyance,
  Climbing,
  Delusion,
  Diminution,
  DragonControl,
  ESP,
  ExtraHealing,
  FireResistance,
  Flying,
  GaseousForm,
  GiantControl,
  GiantStrength,
  Growth,
  Healing,
  Heroism,
  HumanControl,
  Invisibility,
  Invulnerability,
  Levitation,
  Longevity,
  OilOfEtherealness,
  OilOfSlipperiness,
  PhiltreOfLove,
  PhiltreOfPersuasiveness,
  PlantControl,
  PolymorphSelf,
  Poison,
  Speed,
  SuperHeroism,
  SweetWater,
  TreasureFinding,
  UndeadControl,
  WaterBreathing,
}

export const treasurePotion: Table<TreasurePotion> = {
  sides: 100,
  entries: [
    { range: [1, 3], command: TreasurePotion.AnimalControl },
    { range: [4, 6], command: TreasurePotion.Clairaudience },
    { range: [7, 9], command: TreasurePotion.Clairvoyance },
    { range: [10, 12], command: TreasurePotion.Climbing },
    { range: [13, 15], command: TreasurePotion.Delusion },
    { range: [16, 18], command: TreasurePotion.Diminution },
    { range: [19, 20], command: TreasurePotion.DragonControl },
    { range: [21, 23], command: TreasurePotion.ESP },
    { range: [24, 26], command: TreasurePotion.ExtraHealing },
    { range: [27, 29], command: TreasurePotion.FireResistance },
    { range: [30, 32], command: TreasurePotion.Flying },
    { range: [33, 34], command: TreasurePotion.GaseousForm },
    { range: [35, 36], command: TreasurePotion.GiantControl },
    { range: [37, 39], command: TreasurePotion.GiantStrength },
    { range: [40, 41], command: TreasurePotion.Growth },
    { range: [42, 47], command: TreasurePotion.Healing },
    { range: [48, 49], command: TreasurePotion.Heroism },
    { range: [50, 51], command: TreasurePotion.HumanControl },
    { range: [52, 54], command: TreasurePotion.Invisibility },
    { range: [55, 57], command: TreasurePotion.Invulnerability },
    { range: [58, 60], command: TreasurePotion.Levitation },
    { range: [61, 63], command: TreasurePotion.Longevity },
    { range: [64, 66], command: TreasurePotion.OilOfEtherealness },
    { range: [67, 69], command: TreasurePotion.OilOfSlipperiness },
    { range: [70, 72], command: TreasurePotion.PhiltreOfLove },
    { range: [73, 75], command: TreasurePotion.PhiltreOfPersuasiveness },
    { range: [76, 78], command: TreasurePotion.PlantControl },
    { range: [79, 81], command: TreasurePotion.PolymorphSelf },
    { range: [82, 84], command: TreasurePotion.Poison },
    { range: [85, 87], command: TreasurePotion.Speed },
    { range: [88, 90], command: TreasurePotion.SuperHeroism },
    { range: [91, 93], command: TreasurePotion.SweetWater },
    { range: [94, 96], command: TreasurePotion.TreasureFinding },
    { range: [97], command: TreasurePotion.UndeadControl },
    { range: [98, 100], command: TreasurePotion.WaterBreathing },
  ],
};
