import type { Table } from './dungeonTypes';

export enum TreasureRing {
  Contrariness,
  Delusion,
  DjinniSummoning,
  ElementalCommand,
  FeatherFalling,
  FireResistance,
  FreeAction,
  HumanInfluence,
  Invisibility,
  MammalControl,
  MultipleWishes,
  Protection,
  Regeneration,
  ShootingStars,
  SpellStoring,
  SpellTurning,
  Swimming,
  Telekinesis,
  ThreeWishes,
  Warmth,
  WaterWalking,
  Weakness,
  Wizardry,
  XRayVision,
}

export const treasureRings: Table<TreasureRing> = {
  sides: 100,
  entries: [
    { range: [1, 6], command: TreasureRing.Contrariness },
    { range: [7, 12], command: TreasureRing.Delusion },
    { range: [13, 14], command: TreasureRing.DjinniSummoning },
    { range: [15], command: TreasureRing.ElementalCommand },
    { range: [16, 21], command: TreasureRing.FeatherFalling },
    { range: [22, 27], command: TreasureRing.FireResistance },
    { range: [28, 30], command: TreasureRing.FreeAction },
    { range: [31, 33], command: TreasureRing.HumanInfluence },
    { range: [34, 40], command: TreasureRing.Invisibility },
    { range: [41, 43], command: TreasureRing.MammalControl },
    { range: [44], command: TreasureRing.MultipleWishes },
    { range: [45, 60], command: TreasureRing.Protection },
    { range: [61], command: TreasureRing.Regeneration },
    { range: [62, 63], command: TreasureRing.ShootingStars },
    { range: [64, 65], command: TreasureRing.SpellStoring },
    { range: [66, 69], command: TreasureRing.SpellTurning },
    { range: [70, 75], command: TreasureRing.Swimming },
    { range: [76, 77], command: TreasureRing.Telekinesis },
    { range: [78, 79], command: TreasureRing.ThreeWishes },
    { range: [80, 85], command: TreasureRing.Warmth },
    { range: [86, 90], command: TreasureRing.WaterWalking },
    { range: [91, 98], command: TreasureRing.Weakness },
    { range: [99], command: TreasureRing.Wizardry },
    { range: [100], command: TreasureRing.XRayVision },
  ],
};
