import type { Table } from './dungeonTypes';

export enum TreasureIronFlaskContent {
  Empty,
  AirElemental,
  DemonTypeIToIII,
  DemonTypeIVToVI,
  DevilLesser,
  DevilGreater,
  Djinni,
  EarthElemental,
  Efreeti,
  FireElemental,
  InvisibleStalker,
  Mezzodaemon,
  NightHag,
  Nycadaemon,
  Rakshasa,
  Salamander,
  WaterElemental,
  WindWalker,
  Xorn,
}

export const treasureIronFlask: Table<TreasureIronFlaskContent> = {
  sides: 100,
  entries: [
    { range: [1, 50], command: TreasureIronFlaskContent.Empty },
    { range: [51, 54], command: TreasureIronFlaskContent.AirElemental },
    { range: [55, 56], command: TreasureIronFlaskContent.DemonTypeIToIII },
    { range: [57], command: TreasureIronFlaskContent.DemonTypeIVToVI },
    { range: [58, 59], command: TreasureIronFlaskContent.DevilLesser },
    { range: [60], command: TreasureIronFlaskContent.DevilGreater },
    { range: [61, 65], command: TreasureIronFlaskContent.Djinni },
    { range: [66, 69], command: TreasureIronFlaskContent.EarthElemental },
    { range: [70, 72], command: TreasureIronFlaskContent.Efreeti },
    { range: [73, 76], command: TreasureIronFlaskContent.FireElemental },
    { range: [77, 81], command: TreasureIronFlaskContent.InvisibleStalker },
    { range: [82, 83], command: TreasureIronFlaskContent.Mezzodaemon },
    { range: [84, 85], command: TreasureIronFlaskContent.NightHag },
    { range: [86], command: TreasureIronFlaskContent.Nycadaemon },
    { range: [87, 89], command: TreasureIronFlaskContent.Rakshasa },
    { range: [90, 93], command: TreasureIronFlaskContent.Salamander },
    { range: [94, 97], command: TreasureIronFlaskContent.WaterElemental },
    { range: [98, 99], command: TreasureIronFlaskContent.WindWalker },
    { range: [100], command: TreasureIronFlaskContent.Xorn },
  ],
};
