import type { Table } from './dungeonTypes';

export enum TreasureMiscMagicE4 {
  LibramOfGainfulConjuration,
  LibramOfIneffableDamnation,
  LibramOfSilverMagic,
  LyreOfBuilding,
  ManualOfBodilyHealth,
  ManualOfGainfulExercise,
  ManualOfGolems,
  ManualOfPuissantSkillAtArms,
  ManualOfQuicknessOfAction,
  ManualOfStealthyPilfering,
  MattockOfTheTitans,
  MaulOfTheTitans,
  MedallionOfESP,
  MedallionOfThoughtProjection,
  MirrorOfLifeTrapping,
  MirrorOfMentalProwess,
  MirrorOfOpposition,
  NecklaceOfAdaptation,
  NecklaceOfMissiles,
  NecklaceOfPrayerBeads,
  NecklaceOfStrangulation,
  NetOfEntrapment,
  NetOfSnaring,
  NolzursMarvelousPigments,
  PearlOfPower,
  PearlOfWisdom,
  PeriaptOfFoulRotting,
  PeriaptOfHealth,
  PeriaptOfProofAgainstPoison,
  PeriaptOfWoundClosure,
  PhylacteryOfFaithfulness,
  PhylacteryOfLongYears,
  PhylacteryOfMonstrousAttention,
  PipesOfTheSewers,
  PortableHole,
  QuaalsFeatherToken,
}

export const treasureMiscMagicE4: Table<TreasureMiscMagicE4> = {
  sides: 100,
  entries: [
    { range: [1], command: TreasureMiscMagicE4.LibramOfGainfulConjuration },
    { range: [2], command: TreasureMiscMagicE4.LibramOfIneffableDamnation },
    { range: [3], command: TreasureMiscMagicE4.LibramOfSilverMagic },
    { range: [4], command: TreasureMiscMagicE4.LyreOfBuilding },
    { range: [5], command: TreasureMiscMagicE4.ManualOfBodilyHealth },
    { range: [6], command: TreasureMiscMagicE4.ManualOfGainfulExercise },
    { range: [7], command: TreasureMiscMagicE4.ManualOfGolems },
    {
      range: [8],
      command: TreasureMiscMagicE4.ManualOfPuissantSkillAtArms,
    },
    { range: [9], command: TreasureMiscMagicE4.ManualOfQuicknessOfAction },
    { range: [10], command: TreasureMiscMagicE4.ManualOfStealthyPilfering },
    { range: [11], command: TreasureMiscMagicE4.MattockOfTheTitans },
    { range: [12], command: TreasureMiscMagicE4.MaulOfTheTitans },
    { range: [13, 15], command: TreasureMiscMagicE4.MedallionOfESP },
    {
      range: [16, 17],
      command: TreasureMiscMagicE4.MedallionOfThoughtProjection,
    },
    { range: [18], command: TreasureMiscMagicE4.MirrorOfLifeTrapping },
    { range: [19], command: TreasureMiscMagicE4.MirrorOfMentalProwess },
    { range: [20], command: TreasureMiscMagicE4.MirrorOfOpposition },
    { range: [21, 23], command: TreasureMiscMagicE4.NecklaceOfAdaptation },
    { range: [24, 27], command: TreasureMiscMagicE4.NecklaceOfMissiles },
    {
      range: [28, 33],
      command: TreasureMiscMagicE4.NecklaceOfPrayerBeads,
    },
    { range: [34, 35], command: TreasureMiscMagicE4.NecklaceOfStrangulation },
    { range: [36, 38], command: TreasureMiscMagicE4.NetOfEntrapment },
    { range: [39, 42], command: TreasureMiscMagicE4.NetOfSnaring },
    {
      range: [43, 44],
      command: TreasureMiscMagicE4.NolzursMarvelousPigments,
    },
    { range: [45, 46], command: TreasureMiscMagicE4.PearlOfPower },
    { range: [47, 48], command: TreasureMiscMagicE4.PearlOfWisdom },
    { range: [49, 50], command: TreasureMiscMagicE4.PeriaptOfFoulRotting },
    { range: [51, 53], command: TreasureMiscMagicE4.PeriaptOfHealth },
    {
      range: [54, 60],
      command: TreasureMiscMagicE4.PeriaptOfProofAgainstPoison,
    },
    { range: [61, 64], command: TreasureMiscMagicE4.PeriaptOfWoundClosure },
    {
      range: [65, 70],
      command: TreasureMiscMagicE4.PhylacteryOfFaithfulness,
    },
    { range: [71, 74], command: TreasureMiscMagicE4.PhylacteryOfLongYears },
    {
      range: [75, 76],
      command: TreasureMiscMagicE4.PhylacteryOfMonstrousAttention,
    },
    { range: [77, 84], command: TreasureMiscMagicE4.PipesOfTheSewers },
    { range: [85], command: TreasureMiscMagicE4.PortableHole },
    { range: [86, 100], command: TreasureMiscMagicE4.QuaalsFeatherToken },
  ],
};
