import type { Table } from './dungeonTypes';

export enum TreasureArtifactOrRelic {
  AxeOfTheDwarvishLords = 1,
  BabaYagasHut,
  CodexOfTheInfinitePlanes,
  CrownOfMight,
  CrystalOfTheEbonFlame,
  CupAndTalismanOfAlAkbar,
  EyeOfVecna,
  HandOfVecna,
  HewardsMysticalOrgan,
  HornOfChange,
  InvulnerableCoatOfArnd,
  IronFlaskOfTuernyTheMerciless,
  JacinthOfInestimableBeauty,
  JohydeesMask,
  KurothsQuill,
  MaceOfCuthbert,
  MachineOfLumTheMad,
  MightyServantOfLeukO,
  OrbOfTheDragonkind,
  OrbOfMight,
  QueenEhlissasMarvelousNightingale,
  RecorderOfYeCind,
  RingOfGaxx,
  RodOfSevenParts,
  SceptreOfMight,
  SwordOfKas,
  TeethOfDahlverNar,
  ThroneOfTheGods,
  WandOfOrcus,
}

export const treasureArtifactOrRelic: Table<TreasureArtifactOrRelic> = {
  sides: 100,
  entries: [
    { range: [1], command: TreasureArtifactOrRelic.AxeOfTheDwarvishLords },
    { range: [2], command: TreasureArtifactOrRelic.BabaYagasHut },
    {
      range: [3, 4],
      command: TreasureArtifactOrRelic.CodexOfTheInfinitePlanes,
    },
    { range: [5, 20], command: TreasureArtifactOrRelic.CrownOfMight },
    { range: [21], command: TreasureArtifactOrRelic.CrystalOfTheEbonFlame },
    {
      range: [22],
      command: TreasureArtifactOrRelic.CupAndTalismanOfAlAkbar,
    },
    { range: [23, 24], command: TreasureArtifactOrRelic.EyeOfVecna },
    { range: [25], command: TreasureArtifactOrRelic.HandOfVecna },
    { range: [26], command: TreasureArtifactOrRelic.HewardsMysticalOrgan },
    { range: [27], command: TreasureArtifactOrRelic.HornOfChange },
    {
      range: [28, 29],
      command: TreasureArtifactOrRelic.InvulnerableCoatOfArnd,
    },
    {
      range: [30, 31],
      command: TreasureArtifactOrRelic.IronFlaskOfTuernyTheMerciless,
    },
    {
      range: [32],
      command: TreasureArtifactOrRelic.JacinthOfInestimableBeauty,
    },
    { range: [33], command: TreasureArtifactOrRelic.JohydeesMask },
    { range: [34, 35], command: TreasureArtifactOrRelic.KurothsQuill },
    { range: [36, 37], command: TreasureArtifactOrRelic.MaceOfCuthbert },
    { range: [38, 38], command: TreasureArtifactOrRelic.MachineOfLumTheMad },
    { range: [39, 40], command: TreasureArtifactOrRelic.MightyServantOfLeukO },
    { range: [41, 47], command: TreasureArtifactOrRelic.OrbOfTheDragonkind },
    { range: [48, 63], command: TreasureArtifactOrRelic.OrbOfMight },
    {
      range: [64],
      command: TreasureArtifactOrRelic.QueenEhlissasMarvelousNightingale,
    },
    { range: [65, 66], command: TreasureArtifactOrRelic.RecorderOfYeCind },
    { range: [67, 68], command: TreasureArtifactOrRelic.RingOfGaxx },
    { range: [69, 74], command: TreasureArtifactOrRelic.RodOfSevenParts },
    { range: [75, 91], command: TreasureArtifactOrRelic.SceptreOfMight },
    { range: [92], command: TreasureArtifactOrRelic.SwordOfKas },
    { range: [93, 98], command: TreasureArtifactOrRelic.TeethOfDahlverNar },
    { range: [99], command: TreasureArtifactOrRelic.ThroneOfTheGods },
    { range: [100], command: TreasureArtifactOrRelic.WandOfOrcus },
  ],
};
