import type { Table } from './dungeonTypes';

export enum TreasureMiscWeapon {
  ArrowPlus1,
  ArrowPlus2,
  ArrowPlus3,
  ArrowOfSlaying,
  AxePlus1,
  AxePlus2,
  AxePlus2Throwing,
  AxePlus3,
  BattleAxePlus1,
  BoltPlus2,
  BowPlus1,
  CrossbowOfAccuracyPlus3,
  CrossbowOfDistance,
  CrossbowOfSpeed,
  DaggerPlus1VsSmall,
  DaggerPlus2VsLarge,
  DaggerOfVenom,
  FlailPlus1,
  HammerPlus1,
  HammerPlus2,
  HammerPlus3DwarvenThrower,
  HammerOfThunderbolts,
  JavelinPlus2,
  MacePlus1,
  MacePlus2,
  MaceOfDisruption,
  MacePlus4,
  MilitaryPickPlus1,
  MorningStarPlus1,
  ScimitarPlus2,
  SlingOfSeekingPlus2,
  SpearPlus1,
  SpearPlus2,
  SpearPlus3,
  SpearCursedBackbiter,
  TridentPlus3,
}

export const treasureMiscWeapons: Table<TreasureMiscWeapon> = {
  sides: 100,
  entries: [
    { range: [1, 8], command: TreasureMiscWeapon.ArrowPlus1 },
    { range: [9, 12], command: TreasureMiscWeapon.ArrowPlus2 },
    { range: [13, 14], command: TreasureMiscWeapon.ArrowPlus3 },
    { range: [15], command: TreasureMiscWeapon.ArrowOfSlaying },
    { range: [16, 20], command: TreasureMiscWeapon.AxePlus1 },
    { range: [21, 22], command: TreasureMiscWeapon.AxePlus2 },
    { range: [23], command: TreasureMiscWeapon.AxePlus2Throwing },
    { range: [24], command: TreasureMiscWeapon.AxePlus3 },
    { range: [25, 27], command: TreasureMiscWeapon.BattleAxePlus1 },
    { range: [28, 32], command: TreasureMiscWeapon.BoltPlus2 },
    { range: [33, 35], command: TreasureMiscWeapon.BowPlus1 },
    { range: [36], command: TreasureMiscWeapon.CrossbowOfAccuracyPlus3 },
    { range: [37], command: TreasureMiscWeapon.CrossbowOfDistance },
    { range: [38], command: TreasureMiscWeapon.CrossbowOfSpeed },
    { range: [39, 46], command: TreasureMiscWeapon.DaggerPlus1VsSmall },
    { range: [47, 50], command: TreasureMiscWeapon.DaggerPlus2VsLarge },
    { range: [51], command: TreasureMiscWeapon.DaggerOfVenom },
    { range: [52, 56], command: TreasureMiscWeapon.FlailPlus1 },
    { range: [57, 60], command: TreasureMiscWeapon.HammerPlus1 },
    { range: [61, 62], command: TreasureMiscWeapon.HammerPlus2 },
    { range: [63], command: TreasureMiscWeapon.HammerPlus3DwarvenThrower },
    { range: [64], command: TreasureMiscWeapon.HammerOfThunderbolts },
    { range: [65, 67], command: TreasureMiscWeapon.JavelinPlus2 },
    { range: [68, 72], command: TreasureMiscWeapon.MacePlus1 },
    { range: [73, 75], command: TreasureMiscWeapon.MacePlus2 },
    { range: [76], command: TreasureMiscWeapon.MaceOfDisruption },
    { range: [77], command: TreasureMiscWeapon.MacePlus4 },
    { range: [78, 80], command: TreasureMiscWeapon.MilitaryPickPlus1 },
    { range: [81, 83], command: TreasureMiscWeapon.MorningStarPlus1 },
    { range: [84, 88], command: TreasureMiscWeapon.ScimitarPlus2 },
    { range: [89], command: TreasureMiscWeapon.SlingOfSeekingPlus2 },
    { range: [90, 94], command: TreasureMiscWeapon.SpearPlus1 },
    { range: [95, 96], command: TreasureMiscWeapon.SpearPlus2 },
    { range: [97], command: TreasureMiscWeapon.SpearPlus3 },
    { range: [98, 99], command: TreasureMiscWeapon.SpearCursedBackbiter },
    { range: [100], command: TreasureMiscWeapon.TridentPlus3 },
  ],
};
