import {
  NAVIGATION_PENDING_RESOLVERS,
  NAVIGATION_PREVIEW_FACTORIES,
  NAVIGATION_REGISTRY_OUTCOMES,
  NAVIGATION_RENDER_ADAPTERS,
  NAVIGATION_CHILD_POST_PROCESSORS,
  NAVIGATION_TABLE_DEFINITIONS,
} from '.';

export type NavigationTableId =
  (typeof NAVIGATION_TABLE_DEFINITIONS)[number]['id'];

export const NAVIGATION_TABLE_ID_LIST: ReadonlyArray<NavigationTableId> =
  NAVIGATION_TABLE_DEFINITIONS.map((def) => def.id);

export const NAVIGATION_TABLE_HEADINGS = Object.fromEntries(
  NAVIGATION_TABLE_DEFINITIONS.map((def) => [def.id, def.heading])
) as Record<NavigationTableId, string>;

export {
  NAVIGATION_PENDING_RESOLVERS,
  NAVIGATION_PREVIEW_FACTORIES,
  NAVIGATION_REGISTRY_OUTCOMES,
  NAVIGATION_RENDER_ADAPTERS,
  NAVIGATION_CHILD_POST_PROCESSORS,
  NAVIGATION_TABLE_DEFINITIONS,
};
